.TH pokemmo "6" "December 2017" "PokeMMO" "Online game based on the Pokemon universe"
.SH NAME
pokemmo \- is a free to play mmorpg, come join a growing community as you level
up and discover new monsters.
.br
.PP
.SH DESCRIPTION
.br
PokeMMO is based on the Pokemon games in the portable version Game Boy Advance,
a remake of one of the most classic versions of the game.
.PP
In this game, you can play as you would on the portable video game,
but you can face other players and even form groups with your friends,
do joint battles and group missions.
.PP
You can call them to duel with you or even watch the fight with other people.
.br
.PP
.SH REGISTER - FREE TO PLAY
.br
To play this game, you need to make a free registration
on the official website - https://pokemmo.eu/account
.br
.PP
.SH IMPORTANT REQUEST
.br
You need to insert into the hidden home directory (.pokemmo/rom)
the roms of the Pokemon Game Boy Advance version.
.PP
Locate compatible *ROMS* using the ingame menu.
.PP
.br
* Current Required Compatible ROMS: Black/White 1 (EN/FR/ES/DE/IT/KO)
.br
* Current Optional Content Compatible ROMS: Fire Red, Emerald (EN/FR/ES/DE/IT)
.br
* Current Optional Visuals Compatible ROMS: HeartGold, SoulSilver
.br
.PP
.TP
.B You must have the legal right to use that rom.
.TP
.B We will not supply you with the roms, or help you find them as they are copyrighted.
.br
.PP
.SH AUTHOR
.br
The permitted usage of the PokeMMO game client is defined by a non-free license.
.br
The content of this license can be found in the game client after an account's
first login or at https://pokemmo.eu/tos
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao],
for the Debian project (but may be used by others).
