.TH pokemmo "6" "December 2017" "PokeMMO" "Multiplayer online game based on the Pokemon universe"
.SH NAME
pokemmo \- is a free to play mmorpg, come join a growing community as you level
up and discover new monsters.
.br
.PP
.SH SYNOPSIS
.B pokemmo
[
.BI - options
]
.br
.PP
.SH DESCRIPTION
.br
PokeMMO is an emulator of several popular console games with additional features
and multiplayer capabilities.
.PP
In this game, you can play as you would on the portable video game,
but you can face other players and even form groups with your friends,
do joint battles and group missions.
.PP
You can call them to duel with you or even watch the fight with other people.
.PP
This launcher assists with the download, installation, and maintenance of
the game client.
.br
.PP
.SH REGISTER
.br
To play this game, you need to make a free registration
on the official website - https://pokemmo.eu/account
.br
.PP
.SH IMPORTANT REQUEST
.br
This program downloads and installs the PokeMMO client to a user's home directory.
.PP
You need to enter in the hidden personal directory (**$HOME/.local/share/pokemmo/roms**)
the roms of the games in the versions **Game Boy Advance** and **Nintendo DS**.
.PP
Locate compatible *ROMS* using the ingame menu:
.PP
.br
* Current Required Compatible ROMS: Black/White 1 (NDS)
.br
* Current Optional Content Compatible ROMS: Fire Red, Emerald (GBA)
.br
* Current Optional Visuals Compatible ROMS: HeartGold, SoulSilver (NDS)
.br
.PP
.TP
.B You must have the legal right to use that rom.
.TP
.B We will not supply you with the roms, or help you find them as they are copyrighted.
.br
.PP
.SH OPTIONS
.TP
.B -h
Displays help text.
.TP
.B -H <dir>
Defines the PokeMMO directory to the target, instead of $HOME/.local/share/pokemmo
.TP
.B -v
Verbose output in stdout.
.TP
.B --debug
Enables debugging of child java processes (Client and Updater)
.TP
.B --swr
When launching, the client will attempt to use a software renderer if one is available.
If the client is in a Mesa3D environment, LIBGL_ALWAYS_SOFTWARE will be enabled.
Otherwise the internal LWJGL2 swr will be enabled.
.TP
.B --reverify
Reverify the contents of the PokeMMO directory using the bootstrapper. This process is non-destructive.
.TP
.B --skip-java-ram-opts
Use the operating system's default settings for java RAM allocation (-Xmx & -Xms)
.br
.PP
.SH AUTHOR
.br
The PokeMMO game client is developed by PokeMMO.eu <admin@pokemmo.eu>.
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao],
for the Debian project (but may be used by others).
